from pydantic import BaseModel, Field, ConfigDict
from typing import Literal, Optional, List, Dict, Any

class ClaimContext(BaseModel):

    claim_id: str = Field(description="Unique identifier for the claim")
    description: str = Field(description="Text description of the incident")
    policy_type: Literal["Comprehensive", "Third-Party"] = Field(description="Type of the insurance policy")
    claim_amount: float = Field(description="The monetary claim amount specified")
    past_claims: int = Field(default=0, description="Number of past claims by the user")
    documents_status: Literal["Complete", "Missing"] = Field(description="Status of the attached documents")
    image_provided: bool = Field(default=False, description="Whether an image was provided with the claim")
    image_base64: Optional[str] = Field(default=None, description="The base64 encoded image string if provided")

class Agent1Output(BaseModel):
    text: Optional[str] = Field(default=None, description="Optional raw text or commentary generated by the model")
    completeness_score: float = Field(description="Score from 0.0 to 1.0 indicating field completeness")
    missing_fields: List[str] = Field(description="List of fields that are missing or ambiguous", default_factory=list)

class Agent2Output(BaseModel):
    text: Optional[str] = Field(default=None, description="Optional raw text or commentary generated by the model")
    coverage_valid: bool = Field(description="True if the claim is conceptually covered under the policy")
    reason: str = Field(description="Explanation of coverage validation")

class Agent3Output(BaseModel):
    text: Optional[str] = Field(default=None, description="Optional raw text or commentary generated by the model")
    fraud_risk: Literal["low", "medium", "high"] = Field(description="Assessed fraud risk level")
    reason: str = Field(description="Explanation for the assigned fraud risk")

class Agent4Output(BaseModel):
    text: Optional[str] = Field(default=None, description="Optional raw text or commentary generated by the model")
    damage_severity: Literal["minor", "moderate", "major", "not_applicable"] = Field(description="Assessed damage severity from the image")
    reason: str = Field(description="Explanation based on the visual evidence provided")

class Agent5Output(BaseModel):
    text: Optional[str] = Field(default=None, description="Optional raw text or commentary generated by the model")
    final_payout_amount: float = Field(description="The computed payout amount after deductible")
    confidence_score: float = Field(description="The final confidence score of the system (0.0 to 1.0)")
    reason: str = Field(description="Justification for the percentage and computation")

class Agent6Output(BaseModel):
    text: Optional[str] = Field(default=None, description="Optional raw text or commentary generated by the model")
    customer_message: str = Field(description="Message to be sent to the customer")

class AgentExecutionLog(BaseModel):
    agent_name: str
    status: Literal["success", "skipped", "error"]
    details: Optional[Dict[str, Any]] = None

class FinalOutput(BaseModel):
    claim_id: str = Field(alias="Claim ID")
    status: Literal["Approved", "Rejected", "Pending"] = Field(alias="Status")
    estimated_payout: str = Field(alias="Estimated Payout")
    confidence_score: float = Field(alias="Confidence Score")
    reason: str = Field(alias="Reason")
    customer_message: str = Field(alias="Customer Message")
    workflow_log: List[AgentExecutionLog] = Field(default_factory=list)

    class Config:
        populate_by_name = True
